name: 'Comment with Pytest-Benchmark Result'
author: Nils Braun
description: 'Read in the pytest-benchmark result and comment on a pull request'
branding:
  icon: bar-chart
  color: green
inputs:
  benchmark-file:
    description: 'Where to find the json output of pytest-benchmark'
    required: true
    default: 'output.json'
  benchmark-time-unit:
    description: 'Time unit to be used in the resulting benchmark comment'
    required: false
    default: 'seconds'
  comparison-benchmark-file:
    description: 'Where to find the json output of an old pytest-benchmark, for comparison. Empty for no comparison.'
    required: false
    default: ''
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
