name: 'Comment with Pytest-Benchmark Result'
author: Nils Braun
description: 'Read in the pytest-benchmark result and comment on a pull request'
branding:
  icon: bar-chart
  color: green
inputs:
  benchmark-file:
    description: 'Where to find the json output of pytest-benchmark'
    required: true
    default: 'output.json'
  benchmark-metrics:
    description: 'Metrics to display in table'
    required: false
    default: 'name,max,mean,ops,iterations'
  comparison-benchmark-metric:
    description: 'Metric to display in table for compairing with HEAD'
    required: false
    default: 'ops'
  comparison-benchmark-file:
    description: 'Where to find the json output of an old pytest-benchmark, for comparison. Empty for no comparison.'
    required: false
    default: ''
  comparison-higher-is-better:
    description: 'Flag to define if and increased metric is an improvement.'
    required: false
    default: true
  comparison-threshold:
    description: 'Percentage threshold to highlight relevant changes in metric.'
    required: false
    default: 0
  benchmark-title:
    description: 'Title of the comment'
    required: false
    default: 'Result of Benchmark Tests'

  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
